apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-index

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes</title>
    </head>
    <body>
      <h1>Hello from ConfigMap2</h1>
    </body>
    </html>
